import {useEffect,useState} from 'react'
import {api,errorText,setCsrf,snapshotPath} from './api'
import type {User,Snapshot,Detail} from './types'
import {ImportPanel} from './ImportPanel'
import {SnapshotView} from './SnapshotView'
import {AuditPanel} from './AuditPanel'
import {EvaluationPanel} from './EvaluationPanel'
export default function App(){
 const [user,setUser]=useState<User|null>(null),[mode,setMode]=useState(''),[loading,setLoading]=useState(true),[snapshots,setSnapshots]=useState<Snapshot[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('evidence'),[demoIdentity,setDemoIdentity]=useState('admin')
 useEffect(()=>{let active=true;Promise.all([api<{mode:string}>('/auth/mode'),api<User>('/auth/me').catch(()=>null)]).then(([m,u])=>{if(active){setMode(m.mode);setUser(u);setCsrf(u?.csrf_token??'')}}).catch(e=>{if(active)setError(errorText(e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 async function list(){const rows=await api<Snapshot[]>('/snapshots');setSnapshots(rows);return rows}
 useEffect(()=>{if(user)list().catch(e=>setError(errorText(e)))},[user])
 useEffect(()=>{let active=true;setDetail(null);if(selected&&user)api<Detail>(snapshotPath(selected)).then(d=>{if(active)setDetail(d)}).catch(e=>{if(active)setError(errorText(e))});return()=>{active=false}},[selected,user])
 async function loginDemo(){setLoading(true);setError('');try{const u=await api<User>('/auth/demo?identity='+demoIdentity,'POST');setUser(u);setCsrf(u.csrf_token)}catch(e){setError(errorText(e))}finally{setLoading(false)}}
 async function logout(){setError('');try{await api('/auth/logout','POST');setCsrf('');setUser(null);setDetail(null);setSelected('');setSnapshots([])}catch(e){setError(errorText(e))}}
 async function refreshDetail(){if(selected)setDetail(await api<Detail>(snapshotPath(selected)))}
 async function imported(s:Snapshot){await list();setSelected(s.id);setDetail(await api<Detail>(snapshotPath(s.id)));setTab('evidence')}
 async function deleted(){setSelected('');setDetail(null);await list()}
 return <><header><a className="brand" href="/">◈ <span>Identity Risk<br/><strong>Workbench</strong></span></a><div className="header-right"><span className="muted">Alan Vo · Security engineering</span>{user&&<><span>{user.username}</span><button className="quiet" onClick={()=>void logout()}>Sign out</button></>}</div></header><main>
 <section className="hero"><div className="eyebrow">Know who can do what</div><h1>Turn identity exports<br/>into reviewable decisions.</h1><p>Trace inherited access. Find conflicting duties. Preview a safer permission set before anyone changes production.</p></section>
 {error&&<div role="alert" className="notice error">{error}<button className="link" onClick={()=>setError('')}>Dismiss</button></div>}
 {!user?<section className="panel login"><h2>Sign in to your workspace</h2><p>Identity evidence stays behind authenticated sessions. Production uses your organization's single sign-on provider.</p>{loading?<p>Checking session…</p>:mode==='demo'?<><div className="notice">Local demo only. These personas demonstrate separate author and reviewer sessions; they are not real user accounts.</div><label>Demo persona<select aria-label="Demo persona" value={demoIdentity} onChange={e=>setDemoIdentity(e.target.value)}><option value="admin">Administrator</option><option value="analyst">Analyst</option><option value="reviewer">Independent reviewer</option></select></label><button onClick={()=>void loginDemo()}>Enter local demo</button></>:mode==='oidc'?<a className="button" href="/api/auth/login">Continue with SSO</a>:<p>Could not load authentication configuration. Check the API connection and refresh.</p>}</section>:<><nav aria-label="Workspace sections"><button className={tab==='evidence'?'active':''} onClick={()=>setTab('evidence')}>Evidence & reviews</button><button className={tab==='import'?'active':''} onClick={()=>setTab('import')}>Import snapshot</button><button className={tab==='evaluation'?'active':''} onClick={()=>setTab('evaluation')}>Policy evaluation</button>{user.roles.includes('admin')&&<button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}>Audit history</button>}</nav>
 {tab==='evaluation'?<EvaluationPanel/>:tab==='import'?(user.roles.some(r=>r==='reviewer'||r==='admin')?<ImportPanel onImported={s=>{void imported(s).catch(e=>setError(errorText(e)))}}/>:<section className="panel"><p>Your viewer role cannot import evidence.</p></section>):tab==='audit'?<AuditPanel/>:<><section className="panel compact"><label>Evidence snapshot<select aria-label="Evidence snapshot" value={selected} onChange={e=>{setSelected(e.target.value);setError('')}}><option value="">Select a snapshot</option>{snapshots.map(s=><option value={s.id} key={s.id}>{s.name} · {s.summary.identities} identities · {s.summary.findings} findings</option>)}</select></label>{!snapshots.length&&<p>No snapshots yet. Import the synthetic example to explore review and remediation workflows.</p>}</section>{detail?<SnapshotView key={detail.snapshot.id} detail={detail} user={user} onSaved={refreshDetail} onDeleted={deleted}/>:selected?<p role="status">Loading evidence…</p>:<section className="panel empty"><h2>Evidence before action.</h2><p>Select or import a snapshot to inspect grant paths and review its findings.</p><button onClick={()=>setTab('import')}>Start an import</button></section>}</>}
 </>}
 </main><footer>Identity Risk Workbench · v1.0.1 · Alan Vo · <a href="mailto:alanvo@gmail.com">alanvo@gmail.com</a><span>Evidence-based triage. Human-reviewed changes.</span></footer></>
}
