import {useState} from 'react'
import {api,errorText} from './api'
type Metric={threshold_days:number;true_positive:number;false_positive:number;false_negative:number;true_negative:number;precision:number;recall:number;f1:number}
type Result={method:string;training_seed:number;heldout_seed:number;identities_per_split:number;selected_threshold_days:number;candidate_training_metrics:Metric[];heldout_default:Metric;heldout_selected:Metric;limitations:string[]}
export function EvaluationPanel(){
 const [result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function run(){setBusy(true);setError('');try{setResult(await api<Result>('/evaluation'))}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <section className="panel"><div className="eyebrow">Measure the trade-off</div><h2>Policy evaluation</h2><p>Evaluate inactivity thresholds against independent, synthetic lifecycle labels. Dormant legitimate users and recently active departed users intentionally overlap. This runs locally, makes no LLM request, and never changes your policy.</p><button disabled={busy} onClick={()=>void run()}>{busy?'Evaluating…':'Run reproducible evaluation'}</button>{error&&<p role="alert">{error}</p>}{result&&<><p>{result.identities_per_split} identities in each split · training seed {result.training_seed} · held-out seed {result.heldout_seed} · selected threshold {result.selected_threshold_days} days.</p><div className="scroll-table"><table><thead><tr><th>Held-out policy</th><th>Precision</th><th>Recall</th><th>F1</th><th>False positives</th><th>Missed cases</th></tr></thead><tbody>{[result.heldout_default,result.heldout_selected].map((m,i)=><tr key={i}><td>{i===0?'Default':'Selected on training'} · {m.threshold_days} days</td><td>{m.precision}</td><td>{m.recall}</td><td>{m.f1}</td><td>{m.false_positive}</td><td>{m.false_negative}</td></tr>)}</tbody></table></div><ul>{result.limitations.map(l=><li key={l}>{l}</li>)}</ul><details><summary>Training candidate results</summary><pre>{JSON.stringify(result.candidate_training_metrics,null,2)}</pre></details></>}</section>
}
