import {useState} from 'react'
import type {Action,Identity,Plan,Preview,User} from './types'
import {api,errorText,snapshotPath} from './api'
function PreviewView({preview}:{preview:Preview}){return <div className="preview"><p><strong>{preview.resolved.length} resolved</strong> · {preview.introduced.length} introduced · {preview.remaining.length} remaining findings</p>{preview.affected.map(a=><p key={a.identity_id}><code>{a.identity_id}</code>: score {a.score_before} → {a.score_after}. Remaining roles: {a.remaining_roles.join(', ')||'none'}.</p>)}<details><summary>Finding changes</summary><pre>{JSON.stringify({resolved:preview.resolved,introduced:preview.introduced},null,2)}</pre></details><p className="muted">{preview.notice}</p></div>}
function PlanCard({plan,snapshotId,user,onSaved}:{plan:Plan;snapshotId:string;user:User;onSaved:()=>Promise<void>}){
 const [note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const canReview=user.roles.some(r=>r==='admin'||r==='reviewer')&&user.subject!==plan.author&&plan.state==='proposed'
 async function decide(state:string){setBusy(true);setError('');try{await api(snapshotPath(snapshotId)+'/plans/'+plan.id+'/decision','POST',{state,note,version:plan.version});await onSaved()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <article className="finding"><h3>{plan.title} <span className="badge">{plan.state}</span></h3><p className="muted">Proposed by {plan.author}. {plan.reviewed_by&&<>Reviewed by {plan.reviewed_by}: {plan.decision_note}</>}</p><details><summary>Plan actions and impact</summary><pre>{JSON.stringify(plan.actions,null,2)}</pre><PreviewView preview={plan.preview}/></details>{plan.state==='proposed'&&user.subject===plan.author&&<p>A different reviewer must approve or reject this plan.</p>}{canReview&&<fieldset disabled={busy}><label>Plan decision note<textarea value={note} maxLength={4000} onChange={e=>setNote(e.target.value)}/></label><div className="actions"><button disabled={!note.trim()} onClick={()=>void decide('approved')}>Approve plan</button><button className="secondary" disabled={!note.trim()} onClick={()=>void decide('rejected')}>Reject plan</button></div></fieldset>}{error&&<p role="alert" className="error">{error}</p>}</article>
}
export function PlanPanel({snapshotId,identities,plans,user,onSaved}:{snapshotId:string;identities:Identity[];plans:Plan[];user:User;onSaved:()=>Promise<void>}){
 const [actions,setActions]=useState<Action[]>([]),[id,setId]=useState(identities[0]?.id??''),[kind,setKind]=useState<Action['kind']>('remove_role'),[value,setValue]=useState(''),[title,setTitle]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const identity=identities.find(i=>i.id===id),canReview=user.roles.some(r=>r==='admin'||r==='reviewer')
 const options=kind==='remove_role'?identity?.direct_roles??[]:kind==='remove_group'?identity?.groups??[]:[]
 function add(){setActions([...actions,{kind,identity_id:id,...(kind==='disable'?{}:{value})}]);setPreview(null);setValue('')}
 async function run(save:boolean){setBusy(true);setMessage('');try{if(save){await api(snapshotPath(snapshotId)+'/plans','POST',{title,actions});setActions([]);setPreview(null);setTitle('');await onSaved();setMessage('Plan saved for independent review. No external change was executed.')}else{setPreview(null);setPreview(await api<Preview>(snapshotPath(snapshotId)+'/plans/preview','POST',{actions}))}}catch(e){setPreview(null);setMessage(errorText(e))}finally{setBusy(false)}}
 return <section className="panel"><div className="eyebrow">Controlled change</div><h2>Remediation plans</h2><p>Simulate direct grant removals and ownership changes. Approval never executes changes in your identity provider.</p>
 {canReview&&<fieldset disabled={busy}><label>Plan title<input value={title} maxLength={160} onChange={e=>setTitle(e.target.value)}/></label><div className="rule-row"><label>Identity<select aria-label="Identity" value={id} onChange={e=>{setId(e.target.value);setValue('')}}>{identities.map(i=><option key={i.id} value={i.id}>{i.display_name} · {i.id}</option>)}</select></label><label>Action<select aria-label="Action" value={kind} onChange={e=>{setKind(e.target.value as Action['kind']);setValue('')}}><option value="remove_role">Remove direct role</option><option value="remove_group">Remove group membership</option><option value="disable">Disable identity</option><option value="assign_owner">Assign service owner</option></select></label>{kind==='assign_owner'?<label>New accountable owner<input value={value} maxLength={160} onChange={e=>setValue(e.target.value)}/></label>:kind!=='disable'&&<label>Direct grant<select aria-label="Direct grant" value={value} onChange={e=>setValue(e.target.value)}><option value="">Choose a grant</option>{options.map(v=><option key={v}>{v}</option>)}</select></label>}<button className="secondary" disabled={!id||(kind!=='disable'&&!value)||actions.length>=100} onClick={add}>Add action</button></div>
 <ol>{actions.map((a,i)=><li key={i}>{a.identity_id}: {a.kind} {a.value}<button className="link" onClick={()=>{setActions(actions.filter((_,j)=>j!==i));setPreview(null)}} aria-label={'Remove action '+(i+1)}>Remove</button></li>)}</ol><div className="actions"><button disabled={!actions.length} onClick={()=>void run(false)}>Preview plan</button><button className="secondary" disabled={!preview||!title.trim()} onClick={()=>void run(true)}>Save proposed plan</button></div></fieldset>}
 {preview&&<PreviewView preview={preview}/>} {message&&<p role="status">{message}</p>}{plans.map(p=><PlanCard key={p.id+':'+p.version} plan={p} snapshotId={snapshotId} user={user} onSaved={onSaved}/>)}{!plans.length&&<p className="muted">No plans proposed for this snapshot.</p>}</section>
}
