import {useState} from 'react'
import {api,errorText,snapshotPath} from './api'
import type {Advice,Detail,User} from './types'
import {FindingReview} from './FindingReview'
import {PlanPanel} from './PlanPanel'
export function SnapshotView({detail,user,onSaved,onDeleted}:{detail:Detail;user:User;onSaved:()=>Promise<void>;onDeleted:()=>Promise<void>}){
 const [query,setQuery]=useState(''),[severity,setSeverity]=useState('all'),[selected,setSelected]=useState(detail.analysis.identities[0]?.id??''),[advice,setAdvice]=useState<Advice|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[deleteConfirm,setDeleteConfirm]=useState(false)
 const {snapshot,analysis}=detail,canReview=user.roles.some(r=>r==='admin'||r==='reviewer'),isAdmin=user.roles.includes('admin')
 const people=analysis.identities.filter(i=>(i.id+' '+i.display_name).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.risk_score-a.risk_score||a.id.localeCompare(b.id))
 const identity=analysis.identities.find(i=>i.id===selected)
 const findings=analysis.findings.filter(f=>f.identity_id===selected&&(severity==='all'||f.severity===severity))
 async function requestAdvice(external:boolean){setBusy(true);setError('');try{setAdvice(await api<Advice>(snapshotPath(snapshot.id)+'/advice','POST',{external}))}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function remove(){setBusy(true);setError('');try{await api(snapshotPath(snapshot.id)+'?version='+snapshot.version,'DELETE');await onDeleted()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <><section className="panel"><div className="section-top"><div><div className="eyebrow">Immutable evidence snapshot</div><h2>{snapshot.name}</h2><p className="muted">Observed {new Date(snapshot.observed_at).toLocaleString()} · Imported by {snapshot.imported_by}</p></div><div className="actions"><a href={'/api'+snapshotPath(snapshot.id)+'/export/json'}>Export JSON</a><a href={'/api'+snapshotPath(snapshot.id)+'/export/csv'}>Export CSV</a></div></div>
 <div className="stats">{[['Identities',analysis.summary.identities],['Enabled',analysis.summary.enabled],['Privileged',analysis.summary.privileged],['Findings',analysis.summary.findings]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 <details><summary>Scope, policy, and evidence fingerprint</summary><p className="fingerprint">SHA-256: {snapshot.digest}</p><ul>{analysis.limitations.map(l=><li key={l}>{l}</li>)}</ul><pre>{JSON.stringify(analysis.policy,null,2)}</pre></details>
 </section><section className="panel"><div className="eyebrow">Investigation</div><h2>Review identities and effective access</h2><div className="investigation"><div><label>Find identity<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or identifier"/></label><div className="identity-list" aria-label="Identity list">{people.map(i=><button className={'identity '+(selected===i.id?'selected':'')} key={i.id} onClick={()=>setSelected(i.id)}><span><strong>{i.display_name}</strong><small>{i.id} · {i.kind} · {i.enabled?'enabled':'disabled'}</small></span><span className="score">{i.risk_score}</span></button>)}{!people.length&&<p>No identities match this search.</p>}</div></div><div>{identity?<><div className="section-top"><h3>{identity.display_name}</h3><span className="badge">Score {identity.risk_score}/100</span></div><p className="muted">MFA: {identity.mfa===null?'unknown':identity.mfa?'enrolled':'not enrolled'} · Owner: {identity.owner??'not recorded'} · Last sign-in: {identity.last_login?new Date(identity.last_login).toLocaleString():'not recorded'}</p><details><summary>Effective roles, permissions, and paths</summary><p>Direct roles: {identity.direct_roles.join(', ')||'none'}. Groups: {identity.groups.join(', ')||'none'}.</p><pre>{JSON.stringify({roles:identity.effective_roles,permissions:identity.permissions,paths:identity.paths},null,2)}</pre></details><label>Finding severity<select aria-label="Finding severity" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">All severities</option>{['critical','high','medium','low'].map(s=><option key={s}>{s}</option>)}</select></label>{findings.map(f=>{const review=detail.reviews.find(r=>r.finding_id===f.id);return <FindingReview key={f.id+':'+(review?.version??0)} finding={f} review={review} snapshotId={snapshot.id} canReview={canReview} onSaved={onSaved}/>})}{!findings.length&&<p>No matching findings for this identity. This is not a guarantee of safe access.</p>}</>:<p>This snapshot contains no identities.</p>}</div></div></section>
 <PlanPanel snapshotId={snapshot.id} identities={analysis.identities} plans={detail.plans} user={user} onSaved={onSaved}/>
 <section className="panel"><div className="eyebrow">Decision support</div><h2>Review guidance</h2><p>Local guidance needs no API. Optional external advice sends only aggregate counts; no names, IDs, roles, grant paths, or review notes. Your configured provider may charge for a request.</p>{canReview&&<div className="actions"><button disabled={busy} onClick={()=>void requestAdvice(false)}>Local guidance</button><button disabled={busy} className="secondary" onClick={()=>void requestAdvice(true)}>Send aggregate counts for AI advice</button></div>}{advice&&<div className="notice"><strong>{advice.source==='llm'?'Generated advice':'Local deterministic guidance'}</strong><p className="prose">{advice.text}</p><p className="muted">{advice.reason}</p></div>}{error&&<p role="alert" className="error">{error}</p>}</section>
 {isAdmin&&<section className="panel danger"><details><summary>Delete stored snapshot</summary><p>Deletes this snapshot, its reviews, and its plans. Export first if you need to retain the evidence. A digest-only deletion event remains in bounded audit history.</p><label className="checkbox"><input type="checkbox" checked={deleteConfirm} onChange={e=>setDeleteConfirm(e.target.checked)}/>I want to delete this stored snapshot</label><button className="secondary" disabled={!deleteConfirm||busy} onClick={()=>void remove()}>Delete snapshot</button></details></section>}</>
}
